apps/dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^dashboard/orders$', views.showOrders, name="showOrders"),
    url(r'^products$', views.showProducts, name="showProducts"),
    url(r'^products/new$', views.newProduct, name="newProduct"),
    url(r'^products/create$', views.createProduct, name="createProduct"),
    url(r'^products/(?P<id>\d+)/edit$', views.editProduct, name="editProduct"),
    url(r'^products/update$', views.updateProduct, name="updateProduct"),
    url(r'^products/(?P<id>\d+)/destroy$', views.destroyProduct, name="destroyProduct"),
    url(r'^dashboard/orders/show/(?P<id>[0-9]+)$', views.showOrder, name="showOrder")
]

ecommerce/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.shopping.urls', namespace="shopping")),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="db")),
    # url(r'^admin/', admin.site.urls),
]

apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class OrderManager(models.Manager):
    def createCart(self):
        cart = Order.objects.create(status='c')
        return cart.id
    def addToCart(self, postData):
        product = Product.objects.get(id=postData['product_id'])
        item = InventoryItem.objects.get(product=product, is_active=True)
        cart = Order.objects.get(id=postData['cart_id'])
        q = int(postData['quantity'])
        message_to_views = {}
        try:
            orderItem = cart.order_items.get(item=item)
            q = q + orderItem.quantity
            if item.num_avail < q:
                message_to_views['status'] = False
                message_to_views['info'] = "Only {} item(s) left in stock.".format(item.num_avail)
            else:
                orderItem.quantity = q
                orderItem.save()
                message_to_views['status'] = True
                message_to_views['info'] = "Added an additional {} {}(s) to your cart.".format(postData['quantity'], product.name)
        except:
            if item.num_avail < q:
                message_to_views['status'] = False
                message_to_views['info'] = "Only {} item(s) left in stock.".format(item.num_avail)
            else:
                message_to_views['status'] = True
                OrderItem.objects.create(quantity=q,order=cart,item=item)
                message_to_views['info'] = "Added {} item(s) to your cart!".format(q)
        return message_to_views
    def removeOrderItem(self, postData):
        q = OrderItem.objects.get(id=postData['orderItem']).quantity
        OrderItem.objects.get(id=postData['orderItem']).delete()
        return q
    def updateOrderItem(self, postData):
        orderitem = OrderItem.objects.get(id=postData['orderItem'])
        message_to_views = {}
        if int(postData['quantity']) > orderitem.item.num_avail:
            message_to_views['status'] = False
        else:
            q = int(postData['quantity']) - orderitem.quantity
            orderitem.quantity = postData['quantity']
            orderitem.save()
            message_to_views['status'] = True
            message_to_views['quantity'] = q
        return message_to_views

class ProductManager(models.Manager):
    def destroyProduct(self, id):
        # return self.get(id=id).delete()
        print "*"*100
        print "*** Not allowed: Product.objects.destroyProduct(...) (TODO)"
        print "*"*100

    def updateProduct(self, postData):
        print "*"*100
        print "*** Not allowed: Product.objects.updateProduct(...) (TODO)"
        print "*"*100

class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, related_name="products")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProductManager()
    def getCurrentPrice(self):
        return self.items.get(product=self, is_active=True).price
    def getMainImage(self):
        return self.images.get(is_main=True)
    def getActiveInventory(self):
        return self.items.get(is_active=True)

class ProductImage(models.Model):
    url = models.URLField()
    product = models.ForeignKey(Product, related_name="images")
    is_main = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class InventoryItem(models.Model):
    num_avail = models.IntegerField()
    num_sold = models.PositiveIntegerField()
    cost = models.DecimalField( max_digits = 10, decimal_places=2)
    price = models.DecimalField( max_digits = 10, decimal_places=2)
    is_active = models.BooleanField()
    product = models.ForeignKey(Product, related_name="items")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Address(models.Model):
    first_name = models.CharField( max_length = 45 )
    last_name = models.CharField( max_length = 45 )
    address = models.CharField( max_length = 45 )
    address2 = models.CharField( max_length = 45 )
    city = models.CharField( max_length = 45 )
    state = models.CharField( max_length = 45 )
    zip = models.CharField( max_length = 10 )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Billing(models.Model):
    cc_num = models.CharField( max_length = 16 )
    security_code = models.CharField( max_length = 4 )
    exp_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Order(models.Model):
    shipping_cost = models.DecimalField(  max_digits = 10, decimal_places = 2, null = True )
    STATUS_CHOICES = (
        ('c', 'cart'),
        ('i', 'in_process'),
        ('s', 'shipped'),
        ('x', 'cancelled'),
    )
    status = models.CharField( max_length = 1, choices = STATUS_CHOICES )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    items = models.ManyToManyField( InventoryItem, related_name = "orders" )
    address = models.OneToOneField( Address, related_name = "order", null = True )
    billing = models.OneToOneField( Billing, related_name = "order", null = True )
    objects = OrderManager()

class OrderItem(models.Model):
    quantity = models.PositiveSmallIntegerField()
    order = models.ForeignKey(Order, related_name = "order_items" )
    item = models.OneToOneField(InventoryItem, related_name = "order_item" )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def subtotal(self):
        return self.quantity*self.item.price

apps/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .models import Category, Product, ProductImage, InventoryItem
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    # User.objects.create(username='admin', password='Password1')
    return render(request, 'dashboard/index.html')

def showOrders(request):
    return render(request, 'dashboard/orders.html')

def showProducts(request):
    all_products = Product.objects.all()

    paginator = Paginator( all_products, 5 )
    page = request.GET.get( 'page' )
    try:
        products = paginator.page( page )
    except PageNotAnInteger:
        products = paginator.page( 1 )
    except EmptyPage:
        products = paginator.page( paginator.num_pages )

    context = {
        "products": products
    }
    return render(request, 'dashboard/products.html', context )

def newProduct( request ):
    context = {
        "categories": Category.objects.all(),
    }
    return render(request, 'dashboard/newProduct.html', context )

def createProduct( request ):
    pass

def editProduct(request, id):
    context = {
        "product": Product.objects.get( id = id ),
        "categories": Category.objects.all(),
    }
    return render(request, 'dashboard/editProduct.html', context )

def updateProduct(request):
    if request.method == "POST":
        Product.objects.updateProduct( request.POST )

    return redirect( reverse( "db:showProducts" ) )

def destroyProduct(request, id):
    Product.objects.destroyProduct( id = id )

    return redirect( reverse( "db:showProducts" ) )

def showOrder(request, id):
    return render(request, 'dashboard/showOrder.html')

apps/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block pagetitle %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'dashboard/css/base.css' %}">
    <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'dashboard/js/base.js' %}"></script> -->
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Dashboard</a>

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'db:showOrders' %}">Orders</a></li>
            <li><a href="{% url 'db:showProducts' %}">Products</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">log off</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="main_content">
      {% block main %}
      {% endblock %}
    </div>
    <div class="left">
      {% block main1 %}
      {% endblock %}
    </div>
    <div class="right">
      {% block main2 %}
      {% endblock %}
    </div>
    <div class="main_content">
      {% block mainbottom %}
      {% endblock %}
    </div>
  </body>
</html>

apps/dashboard/templates/dashboard/base_1row_1col.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block pagetitle %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'dashboard/css/base.css' %}">
    <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'dashboard/js/base.js' %}"></script> -->
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Dashboard</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'db:showOrders' %}">Orders</a></li>
            <li><a href="{% url 'db:showProducts' %}">Products</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="">log off</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="" style="padding: 1rem;">
      {% block main %}
      {% endblock %}
    </div>
  </body>
</html>

apps/dashboard/templates/dashboard/editProduct.html
{% extends 'dashboard/base_1row_1col.html' %}
{% block pagetitle %}Dashboard - Edit Product{% endblock %}
{% block main %}
<h3>Edit Product - ID {{ product.id }}</h3>
<form action="{% url 'db:updateProduct' %}" method="POST">
  {% csrf_token %}
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-4">
      <input type="text" name="name" class="form-control" value="{{ product.name }}" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-4">
      <!-- <input type="text" name="description" class="form-control" value="{{ product.description }}" /> -->
      <textarea name="description" class="form-control" rows="4">{{ product.description }}</textarea>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Category</label>
    <div class="col-sm-4">
      <select name="category" class="form-control">
        {% for category in categories %}
          <option {% if product.category.id == category.id %}selected{% endif %} value="{{ category.id }}">
            {{ category.name }}
          </option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">or add a new category</label>
    <div class="col-sm-4">
      <input type="text" name="new_category" class="form-control" placeholder="Enter a new category" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Images</label>
    <div class="col-sm-4">
      <table class="table">
        <tr>
          <td><button>Upload</button></td>
        </tr>
        {% for image in product.images.all %}
          <tr>
            <td><img src="{% comment %}{{ image.url }}{% endcomment %}" alt="{{ product.name }}" class="img-thumb" /></td>
            <td>{{ image.url }}</td>
            <td><a href="#">delete</a></td>
            <td>
              <input type="radio" name="image_is_main" value="{{ image.id }}" {% if image.is_main %}checked{% endif %}>main
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
  <div class="form-group row">
    <span class="col-sm-2 col-form-label"></span>
    <div class="col-sm-4">
      <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-info">Cancel</a>
      <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-info">Preview</a>
      <input type="submit" value="Update" class="btn btn-primary" />
    </div>
  </div>
</form>
{% endblock %}

apps/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Admin</title>
  </head>
  <body>
    <h1>Admin Login Page</h1>
    <form class="" action="{% url 'db:showOrders' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label>Username: <input type="text" name="username" class="form-control"></label>
      </div>
      <div class="form-group">
        <label>Password: <input type="password" name="password" class="form-control"></label>
      </div>
      <input type="submit" class="btn btn-primary" value="Log In">
    </form>
  </body>
</html>

apps/dashboard/templates/dashboard/newProduct.html
{% extends 'dashboard/base_1row_1col.html' %}
{% block pagetitle %}Dashboard - Add Product{% endblock %}
{% block main %}
<h3>Add Product</h3>
<form action="{% url 'db:updateProduct' %}" method="POST">
  {% csrf_token %}
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-4">
      <input type="text" name="name" class="form-control" placeholder="Enter product name" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-4">
      <!-- <input type="text" name="description" class="form-control" value="{{ product.description }}" /> -->
      <textarea name="description" class="form-control" rows="4" placeholder="Enter product description"></textarea>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Category</label>
    <div class="col-sm-4">
      <select name="category" class="form-control">
        <option selected disabled value="NULL">Select a category</option>
        {% for category in categories %}
          <option value="{{ category.id }}">
            {{ category.name }}
          </option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">or add a new category</label>
    <div class="col-sm-4">
      <input type="text" name="new_category" class="form-control" placeholder="Enter a new category" />
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Images</label>
    <div class="col-sm-4">
      <table class="table">
        <tr>
          <td><button>Upload</button></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="form-group row">
    <span class="col-sm-2 col-form-label"></span>
    <div class="col-sm-4">
      <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-info">Cancel</a>
      <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-info">Preview</a>
      <input type="submit" value="Add" class="btn btn-primary" />
    </div>
  </div>
</form>
{% endblock %}

apps/dashboard/templates/dashboard/orders.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}Dashboard - Orders{% endblock %}
{% block main %}
  <p>Search Bar and filter menu</p>
  <table class="table table-striped">
    <tr>
      <th>Order ID</th>
      <th>Name</th>
      <th>Date</th>
      <th>Billing Address</th>
      <th>Total</th>
      <th>Status</th>
    </tr>
  </table>
  <p>page numbers</p>
{% endblock %}

apps/dashboard/templates/dashboard/products.html
{% extends 'dashboard/base_1row_1col.html' %}
{% block pagetitle %}Dashboard - Products{% endblock %}
{% block main %}
  <div class="">
    <div class="col-sm-4" style="border: 1px solid lightgrey; border-radius: 10px;">
      Search Bar (TODO)
    </div>
    <div class="col-sm-2 pull-right">
      <button class="btn"><a href="{% url 'db:newProduct' %}">Add new product</a></button>
    </div>
  </div>
  <div class="">
    &nbsp;
  </div>
  <div class="">
    <table class="table table-striped table-bordered table-condensed">
      <tr>
        <th style="width: 10%;">Picture</th>
        <th style="width: 10%;">ID</th>
        <th style="width: 30%;">Name</th>
        <th>Inventory Count</th>
        <th>Quantity Sold</th>
        <th style="width: 10%;">Action</th>
      </tr>
      {% for product in products %}
        <tr>
          <td><img src="{% comment %}{{ product.getMainImage.url }}{% endcomment %}" alt="{{ product.name }}" class="img-thumb" /></a></td>
          <td>{{ product.id }}</td>
          <td>{{ product.name }}</td>
          <td>{{ product.getActiveInventory.num_avail }}</td>
          <td>{{ product.getActiveInventory.num_sold }}</td>
          <td>
            <a href="{% url 'db:editProduct' id=product.id %}">edit</a>
            <a href="{% url 'db:destroyProduct' id=product.id %}">delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div class="pagination">
    <div class="step-links">
      {% if products.has_previous %}
        <a href="?page={{products.previous_page_number}}">previous</a>
      {% endif %}
      {% if products.has_previous and products.has_next %}
        &nbsp;&nbsp;|&nbsp;&nbsp;
      {% endif %}
      {% if products.has_next %}
        <a href="?page={{products.next_page_number}}">next</a>
      {% endif %}
    </div>
    <div class="step-links">
      {% for page in products.paginator.page_range %}
        {% if forloop.counter != 1 %}
          &nbsp;&nbsp;|&nbsp;&nbsp;
        {% endif %}
        {% ifequal page products.number %}
          {{ page }}
        {% else %}
          <a href="?page={{page}}">{{ page }}</a>
        {% endifequal %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

apps/dashboard/templates/dashboard/showOrder.html
{% extends 'dashboard/base.html' %}
{% block pagetitle %}Dashboard - Order #{% endblock %}
{% block main1 %}
  <div class="orderDetails">
    <p>Order ID #</p>
    <br>
    <p>Customer Shipping Info:</p>
    <p>Name: </p>
    <p>Address:</p>
    <p>address</p>
    <p>city, state zip</p>
    <br>
    <p>Customer Billing Info:</p>
    <p>Name: </p>
    <p>Address:</p>
    <p>address</p>
    <p>city, state zip</p>
  </div>
{% endblock %}
{% block main2 %}
  <table class="table table-striped">
    <tr>
      <th>ID</th>
      <th>Item</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
    </tr>
  </table>
  <p>status and price breakdown</p>
{% endblock %}