apps/shopping/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^products$', views.index),
    url(r'^products/byCat/(?P<cat_id>[0-9]+)$', views.showCategory, name="showCategory"),
    url(r'^products/orderBy$', views.setOrderBy, name="orderBy"),
    url(r'^products/(?P<id>[0-9]+)$', views.show, name="show"),
    url(r'^products/(?P<id>[0-9]+)/add$', views.addToCart, name="addToCart"),
    url(r'^products/updateCart$', views.updateCart, name="updateCart"),
    url(r'^products/cart$', views.showCart, name="showCart")
]

ecommerce/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.shopping.urls', namespace="shopping")),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="db")),
    # url(r'^admin/', admin.site.urls),
]

apps/shopping/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/shopping/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from ..dashboard.models import Product, Category, Order
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    if 'cart_id' not in request.session:
        request.session['cart_id'] = Order.objects.createCart()
        request.session['cart_items'] = 0
        request.session['orderBy'] = 'name'
    request.session['category_id'] = 0
    context = {'categories': Category.objects.all(),
               'products': populateProducts(request) }
    return render(request, 'shopping/index.html', context)

def setOrderBy(request):
    if request.method == "POST":
        if request.POST['sort_by'] == 'price':
            request.session['orderBy'] = 'items__price'
        elif request.POST['sort_by'] == 'popularity':
            request.session['orderBy'] = '-items__num_sold'
        else:
            request.session['orderBy'] = request.POST['sort_by']
        if request.session['category_id'] != 0:
            category = Category.objects.get(id=request.session['category_id'])
        else:
            category = "all"
        context = {'categories': Category.objects.all(),
                   'products': populateProducts(request),
                   'category': category}
        return render(request, 'shopping/productDisplay.html', context)

def showCategory(request, cat_id):
    request.session['category_id'] = cat_id
    context = {'categories': Category.objects.all(),
               'products': populateProducts(request),
               'category': Category.objects.get(id=request.session['category_id'])}
    return render(request, 'shopping/index.html', context)

def show(request, id):
    context = {'product': Product.objects.get(id=id) }
    return render(request, 'shopping/productDetails.html', context)

def addToCart(request, id):
    if request.method == 'POST':
        postData = {'product_id': id,
                    'quantity': request.POST['quantity'],
                    'cart_id': request.session['cart_id']}
        item = Order.objects.addToCart(postData)
        messages.add_message(request, messages.INFO, item['info'])
        if item['status']:
            request.session['cart_items'] += int(request.POST['quantity'])
        return redirect('shopping:show', id=id)
    else:
        return redirect('shopping:index')

def updateCart(request):
    if request.method == "POST":
        if request.POST['quantity'] == "0":
            request.session['cart_items'] -= Order.objects.removeOrderItem(request.POST)
            return redirect('shopping:showCart')
        else:
            update = Order.objects.updateOrderItem(request.POST)
            if not update['status']:
                messages.add_message(request, messages.ERROR, "not enough inventory available")
            else:
                request.session['cart_items'] += update['quantity']
        return redirect('shopping:showCart')

def showCart(request):
    cart = Order.objects.get(id=request.session['cart_id'])
    total = 0
    for item in cart.order_items.all():
        total += item.quantity*item.item.price
    context = { 'cart': cart,
                'total': total }
    return render(request, 'shopping/cart.html', context)

def populateProducts(request):
    if request.session['category_id'] == 0:
        cat = ""
        products = Product.objects.all().order_by(request.session['orderBy'])
    else:
        cat = Category.objects.get(id=request.session['category_id'])
        products = Product.objects.filter(category=cat).order_by(request.session['orderBy'])
    paginator = Paginator(products, 15)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return products

apps/shopping/templates/shopping/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block pagetitle %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'shopping/css/base.css' %}">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'shopping/js/base.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'shopping:index' %}">Dojo eCommerce</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'shopping:showCart' %}">Shopping Cart ({{request.session.cart_items}})</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="main_content">
      {% block main %}
      {% endblock %}
    </div>
    <div class="left">
      {% block main1 %}
      {% endblock %}
    </div>
    <div class="right">
      {% block main2 %}
      {% endblock %}
    </div>
    <div class="main_content">
      {% block mainbottom %}
      {% endblock %}
    </div>
  </body>
</html>

apps/shopping/templates/shopping/cart.html
{% extends 'shopping/base.html' %}
{% block pagetitle %}Dojo eCommerce{% endblock %}
{% block main %}
{% if messages %}
  <div class="errors">
  {% for message in messages %}
    <p>{{message}}</p>
  {% endfor %}
  </div>
{% endif %}
  <table class="table table-striped">
    <tr>
      <th>Item</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
    </tr>
    {% for item in cart.order_items.all %}
      <tr>
        <td>{{item.item.product.name}}</td>
        <td>${{item.item.price}}</td>
        <td><form class="" action="{% url 'shopping:updateCart' %}" method="post">
          {% csrf_token %}
          <input type="text" name="quantity" value="{{item.quantity}}" size="1" class="input-center">
          <input type="submit" class="btn btn-link" value="update">
          <input type="hidden" name="orderItem" value="{{item.id}}">
        </form></td>
        <td>${{item.subtotal}}</td>
      </tr>
    {% endfor %}
  </table>
  <p>Total: ${{total}}</p>
  <p><a href="{% url 'shopping:index' %}" class="btn btn-primary">Keep Shopping</a></p>
  <br>
  <br>
  {% endblock %}
  {% block main1 %}
  <h3>Shipping Information</h3>
  <form class="" action="" method="post">
    {% csrf_token %}
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">First Name</label>
      <div class="col-sm-8">
        <input type="text" name="first_name" class="form-control" placeholder="last name">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Last Name</label>
      <div class="col-sm-8">
        <input type="text" name="last_name" class="form-control" placeholder="first name">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Address</label>
      <div class="col-sm-8">
        <input type="text" name="address" class="form-control" placeholder="address">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Address 2</label>
      <div class="col-sm-8">
        <input type="text" name="address2" class="form-control" placeholder="address 2 (optional)">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">City</label>
      <div class="col-sm-8">
        <input type="text" name="city" class="form-control" placeholder="city">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">State</label>
      <div class="col-sm-8">
        <input type="text" name="state" class="form-control" placeholder="state">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Zip</label>
      <div class="col-sm-8">
        <input type="text" name="zip" class="form-control" placeholder="zip">
      </div>
    </div>
    <h3>Billing Information</h3>
    <p><input type="checkbox" class="sameAsShipping"> same as shipping</p>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">First Name</label>
      <div class="col-sm-8">
        <input type="text" name="bfirst_name" class="form-control" placeholder="last name">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Last Name</label>
      <div class="col-sm-8">
        <input type="text" name="blast_name" class="form-control" placeholder="first name">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Address</label>
      <div class="col-sm-8">
        <input type="text" name="baddress" class="form-control" placeholder="address">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Address 2</label>
      <div class="col-sm-8">
        <input type="text" name="baddress2" class="form-control" placeholder="address 2 (optional)">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">City</label>
      <div class="col-sm-8">
        <input type="text" name="bcity" class="form-control" placeholder="city">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">State</label>
      <div class="col-sm-8">
        <input type="text" name="bstate" class="form-control" placeholder="state">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Zip</label>
      <div class="col-sm-8">
        <input type="text" name="bzip" class="form-control" placeholder="zip">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Card Number</label>
      <div class="col-sm-8">
        <input type="text" name="cc" class="form-control" placeholder="cc#">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Security Code</label>
      <div class="col-sm-8">
        <input type="text" name="code" class="form-control" placeholder="xxx">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Expiration</label>
      <div class="col-sm-2">
        <input type="text" name="expmonth" class="form-control" placeholder="mm">
      </div>
      <div class="col-sm-2">
        <input type="text" name="expyear" class="form-control" placeholder="yyyy">
      </div>
    </div>
    <input type="submit" class="btn btn-primary" value="Pay">
  </form>
{% endblock %}

apps/shopping/templates/shopping/index.html
{% extends 'shopping/base.html' %}
{% block pagetitle %}Dojo eCommerce{% endblock %}
{% block main1 %}
  <div class="sidebar">
    <p>search box</p>
    <br>
    <h6>Categories</h6>
    <ul>
      {% for category in categories %}
      {% if category.id|stringformat:'s' == request.session.category_id|stringformat:'s' %}
        <li>{{category.name}} ({{category.products.count}})</li>
      {% else %}
        <li><a href="{% url 'shopping:showCategory' category.id %}" class="selectcat">{{category.name}} ({{category.products.count}})</a></li>
      {% endif %}
      {% endfor %}
      {% if request.session.category_id == 0 %}
        <li><i>show all</i></li>
      {% else %}
        <li><a href="{% url 'shopping:index' %}">show all</a></li>
      {% endif %}
    </ul>
  </div>
{% endblock %}
{% block main2 %}
  {% if request.session.category_id == 0 %}
  <h2 class="categoryname">All Products</h2>
  {% else %}
  <h2 class="categoryname">{{ category.name|title }}s</h2>
  {% endif %}
  <div class="row">
    <div class="col-sm-3">
      <form class="" action="{% url 'shopping:orderBy' %}" method="post" id="sort_form">
        {% csrf_token %}
        Sort by: <select class="form-control" name="sort_by" id="sort_by">
          <option value="name">Name</option>
          <option value="price">Price</option>
          <option value="popularity">Most Popular</option>
        </select>
      </form>
    </div>
    <br>
    <br>
    <div id="products_display">
      <div class="col-sm-3 pull-right">
        <a href="?page=1">first</a> |
        {% if products.has_previous %}
        <a href="?page={{products.previous_page_number}}">previous</a> |
        {% endif %}

        <span class="current">
          Page {{ products.number }} of {{ products.paginator.num_pages }}
        </span>
        {% if products.has_next %}
        <a href="?page={{ products.next_page_number }}"> | next</a>
        {% endif %}
      </div>
    <br>
    {% for product in products %}
    <div class="product_display">
      <a href="{% url 'shopping:show' id=product.id %}"><img src="{% comment %}{{product.getMainImage.url}}{% endcomment %}" alt="{{product.name}}" class="img-med"></a>
      <p>{{product.name|truncatechars:25}} <span class="pull-right">${{product.getCurrentPrice}}</span></p>
    </div>
    {% endfor %}
    <br>
    <div class="pagination">
      <span class="step-links">
        {% for page in products.paginator.page_range %}
        {% if forloop.counter != 1 %}&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;{% endif %}
        {% ifequal page products.number %}
        {{ page }}
        {% else %}
        <a href="?page={{page}}">{{ page }}</a>
        {% endifequal %}
        {% endfor %}
      </span>
    </div>
    </div>
  </div>
{% endblock %}

apps/shopping/templates/shopping/productDetails.html
{% extends 'shopping/base.html' %}
{% block pagetitle %}Dojo eCommerce{% endblock %}
{% block main1 %}
  <p><a href="{% url 'shopping:index' %}">Go Back</a></p>
  <h3>Product Name</h3>
  <p><img src="{% comment %}{{product.getMainImage.url}}{% endcomment %}" alt="{{product.name}}" class="img-lg"></p>
  {% for image in product.images.all %}
    <img src="{% comment %}{{image.url}}{% endcomment %}" alt="alt images" class="img-sm">
  {% endfor %}
{% endblock %}
{% block main2 %}
  <p>{{product.description}}</p>
  <p>Price: ${{product.getCurrentPrice}}</p>
  <form class="" action="{% url 'shopping:addToCart' id=product.id %}" method="post">
    {% csrf_token %}
    <label>Quantity: <input type="text" name="quantity" class="form-control"></label>
    <input type="submit" name="" value="Add To Cart">
  </form>
  {% if messages %}
    <div class="errors">
    {% for message in messages %}
      <p>{{message}}</p>
    {% endfor %}
    </div>
  {% endif %}
{% endblock %}
{% block mainbottom %}
  <h4>Similar Items</h4>
  <a href=""><img src="" alt="other items" class="img-med"></a>
  <a href=""><img src="" alt="other items" class="img-med"></a>
  <a href=""><img src="" alt="other items" class="img-med"></a>
{% endblock %}

apps/shopping/templates/shopping/productDisplay.html
<div class="col-sm-3 pull-right">
  <a href="?page=1">first</a> |
  {% if products.has_previous %}
  <a href="?page={{products.previous_page_number}}">previous</a> |
  {% endif %}

  <span class="current">
    Page {{ products.number }} of {{ products.paginator.num_pages }}
  </span>
  {% if products.has_next %}
  <a href="?page={{ products.next_page_number }}"> | next</a>
  {% endif %}
</div>
</div>
<br>
{% for product in products %}
<div class="product_display">
<a href="{% url 'shopping:show' id=product.id %}"><img src="{% comment %}{{product.getMainImage.url}}{% endcomment %}" alt="{{product.name}}" class="img-med"></a>
<p>{{product.name|truncatechars:25}} <span class="pull-right">${{product.getCurrentPrice}}</span></p>
</div>
{% endfor %}
<br>
<div class="pagination">
<span class="step-links">
  {% for page in products.paginator.page_range %}
  {% if forloop.counter != 1 %}&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;{% endif %}
  {% ifequal page products.number %}
  {{ page }}
  {% else %}
  <a href="?page={{page}}">{{ page }}</a>
  {% endifequal %}
  {% endfor %}
</span>
</div>